version: "3.7"

services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: starwars
      POSTGRES_USER: starwars
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgAdmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
        PGADMIN_DEFAULT_PASSWORD: root
        PGADMIN_LISTEN_PORT: 80
      ports:
        - 8080:80
      volumes:
        - /var/lib/pgadmin
      depends_on:
        - db